### ISSUE TITLE
undefined: sort.Slice errors in /carted/hewly/types and more

### ISSUE THREAD

**Issue by patrickbolle** [carted/themed#2]
```
➜  ~ go get github.com/carted/themed
# github.com/carted/hewly/types
go/src/github.com/carted/hewly/types/array.go:159: undefined: sort.Slice
# github.com/etcd-io/bbolt
go/src/github.com/etcd-io/bbolt/freelist_hmap.go:154: undefined: sort.SliceIsSorted

```
Running Debian, Go v1.7.4

Not too knowledgeable on Go so can't really help much here. Any ideas?

Related/unrelated:
After it finishes installing, there is no /bin folder in ~/go
Just ~/go/pkg and ~/go/src

**Comment by evulse** [comment]
I'm guessing this will just be an old version of Go, we probably should have stated that this requires go 1.10 or later.

**Comment by patrickbolle** [comment]
Ah, will give it a shot. Sorry, should have given that a go!

**Comment by patrickbolle** [comment]
That was it! Upgraded to 1.12 fixed this issue.
